
task :mac_and_cheese => [:boil_water, :buy_pasta, :buy_cheese] do
  puts "Making Mac & Cheese"
end

task :buy_cheese do
  puts "Buying Cheese"
end

task :buy_pasta do
  puts "Buying Pasta"
end

task :boil_water => [:buy_cheese, :buy_pasta] do
  puts "Boiling water"
end

task :go_to_store do
  puts "Going to store"
end