
task :default => :mac_and_cheese

desc "Make Mac & Cheese"
task :mac_and_cheese => [:boil_water, :buy_pasta, :buy_cheese] do
  puts "Making Mac & Cheese"
end

desc "Buy some delicious cheese"
task :buy_cheese do
  puts "Buying Cheese"
end

desc "Buy some quality pasta"
task :buy_pasta do
  puts "Buying Pasta"
end

desc "Boil the water"
task :boil_water => [:buy_cheese, :buy_pasta] do
  puts "Boiling water"
end

task :go_to_store do
  puts "Going to store"
end

namespace :apple do
  task :go_to_store do
    puts "Going to apple store"
  end
end

task :show_current_directory do
  puts "PWD=#{`pwd`}"
end

task :show_stuff do
  puts "ENVS = #{ENV["TOTAL"]}"
end

task :factorial do 
  n = (ENV['N'] || 10).to_i
  fact = 1
  (1..n).each do |i|
    fact = fact * i
  end
  puts "Factorial of #{n} is #{fact}"
end

task :backup do
  mkdir_p "backup"
  cp "Rakefile", "backup/Rakefile"
  cp_r "app", "backup"
end

task :git_status do
  sh "git status"
end